---
image: "corneel27/dao-{arch}"
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
  i386: ghcr.io/hassio-addons/debian-base/i386:stable

