import { defineConfig } from 'vite'
import os from 'node:os'

// Host the browser uses to reach the dev server.  Defaults to the first
// non-internal IPv4 address, so asset URLs generated by Vite (fonts referenced
// from CSS, imported images) keep working when the dev server runs on another
// machine than the browser.  Override with VITE_DEV_HOST when needed, for
// example VITE_DEV_HOST=localhost when tunneling the port over SSH.
function devHost() {
  if (process.env.VITE_DEV_HOST) return process.env.VITE_DEV_HOST
  for (const addresses of Object.values(os.networkInterfaces())) {
    for (const address of addresses ?? []) {
      if (address.family === 'IPv4' && !address.internal) return address.address
    }
  }
  return 'localhost'
}

const host = devHost()
const port = Number(process.env.VITE_DEV_PORT || 5173)

export default defineConfig({
  base: './',
  build: {
    outDir: 'app/static/build',
    emptyOutDir: true,
    manifest: true,
    rollupOptions: {
      input: {
        main: 'assets/main.js'
      }
    }
  },
  server: {
    host: '0.0.0.0',
    port: port,
    strictPort: true,
    origin: `http://${host}:${port}`,
    // Empty by default: localhost and IP addresses are always allowed.
    // Set VITE_DEV_ALLOWED_HOSTS=dao.local,dev.example.com when reaching the
    // server by name or through a reverse proxy.
    allowedHosts: (process.env.VITE_DEV_ALLOWED_HOSTS ?? '')
      .split(',')
      .filter(Boolean),  },
})