import { defaultAllowedOrigins, defineConfig } from 'vite'
import os from 'node:os'

// Host the browser uses to reach the dev server.  Defaults to the first
// non-internal IPv4 address, so asset URLs generated by Vite (fonts referenced
// from CSS, imported images) keep working when the dev server runs on another
// machine than the browser.  Override with VITE_DEV_HOST when needed, for
// example VITE_DEV_HOST=localhost when tunneling the port over SSH.
function devHost() {
  if (process.env.VITE_DEV_HOST) return process.env.VITE_DEV_HOST
  for (const addresses of Object.values(os.networkInterfaces())) {
    for (const address of addresses ?? []) {
      if (address.family === 'IPv4' && !address.internal) return address.address
    }
  }
  return 'localhost'
}

// Origins allowed to fetch the assets.  The page itself is served by Flask on
// another port, so every asset request is cross origin.  Vite only sends the
// CORS headers to localhost by default, which makes the browser discard the
// module and leaves the v2 pages completely unstyled as soon as the browser is
// not on the development machine.  Mirror the allowedHosts rule instead: IP
// addresses and localhost are always accepted, hostnames have to be listed in
// VITE_DEV_ALLOWED_HOSTS.
const ipOrigin = /^https?:\/\/(?:\d{1,3}(?:\.\d{1,3}){3}|\[[0-9a-fA-F:.]+\])(?::\d+)?$/

function hostOrigin(hostname) {
  const escaped = hostname.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return new RegExp(`^https?://${escaped}(?::\\d+)?$`)
}

const allowedHosts = (process.env.VITE_DEV_ALLOWED_HOSTS ?? '')
  .split(',')
  .filter(Boolean)

const allowedOrigins = [
  defaultAllowedOrigins,
  ipOrigin,
  ...allowedHosts.map(hostOrigin),
]

const host = devHost()
const port = Number(process.env.VITE_DEV_PORT || 5173)

export default defineConfig({
  base: './',
  build: {
    outDir: 'app/static/build',
    emptyOutDir: true,
    manifest: true,
    rollupOptions: {
      input: {
        main: 'assets/main.js'
      }
    }
  },
  css: {
    preprocessorOptions: {
      scss: {
        // Bootstrap 5.3 gebruikt intern nog @import en de verouderde
        // globale Sass-functies. Die waarschuwingen kunnen we in onze eigen
        // code niet oplossen, dus onderdrukken we ze voor node_modules.
        // Deprecations in onze eigen .scss blijven wel zichtbaar.
        quietDeps: true,
      },
    },
  },
  server: {
    host: '0.0.0.0',
    port: port,
    strictPort: true,
    origin: `http://${host}:${port}`,
    // Empty by default: localhost and IP addresses are always allowed.
    // Set VITE_DEV_ALLOWED_HOSTS=dao.local,dev.example.com when reaching the
    // server by name or through a reverse proxy.
    allowedHosts: allowedHosts,
    // Without this the browser refuses the assets whenever the application is
    // opened on anything other than localhost; see allowedOrigins above.
    cors: {
      origin: allowedOrigins,
    },
  },
})