name: "Build Dockerfiles Test Run"

on:
  workflow_dispatch:

jobs:
  build_test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Run Build Test
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target dao \
            --generic $GITHUB_REF_NAME
