name: "Publish or test containers"

env:
  BUILD_ARGS: "--test"
  VERSION: "develop"

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish or test images
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "i386"]

    runs-on: ubuntu-latest
    steps:
      # do a test build when it is not a release (or pre-release)
      - name: Set event to release
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "BUILD_ARGS=" >> $GITHUB_ENV

      # checkout the repo
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # Update config.yaml to reflect the correct version
      - name: Update version when release
        if: ${{ github.event_name == 'release' }}
        run: |
          VERSION=$(grep version dao/config.yaml | sed -e 's/^version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Add additional 'stable' tag when this is a non-rc release
      - name: Set stable on a verions without .rc
        shell: bash
        run: |
          if [[ $VERSION == *".rc"* ]]; then
            echo "this is a release candidate, not setting stable or latest tag"
            echo "LATEST=--no-latest" >> $GITHUB_ENV;
            echo "EXTRA_TAG=--additional-tag latest-rc" >> $GITHUB_ENV;
          else
            echo "this is a final release, setting stable tag"
            echo "LATEST=" >> $GITHUB_ENV;
            echo "EXTRA_TAG=--additional-tag stable" >> $GITHUB_ENV
          fi  
       
      # login to GHCR with the repository owner creds
      - name: Login to GHCR
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # fix dependabot[bot] github actor
      - name: Fix dependabot actor name
        if: ${{ github.event_name != 'release' }}
        shell: bash
        run: |
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            echo "ACTOR=dependabot" >> $GITHUB_ENV;
          else
            echo "ACTOR=${{ github.actor }}" >> $GITHUB_ENV;
          fi

      # use hass builder to create generic images
      - name: Publish ${{ matrix.arch }} image
        if: ${{ env.BUILD_ARGS != '--test' }}
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            ${{ env.LATEST }} \
            ${{ env.EXTRA_TAG }} \
            --generic $VERSION \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}" \
            --target dao \
            --docker-hub ghcr.io/${ACTOR} \
            --version $VERSION 

      # use hass builder to create addon images
      - name: Publish ${{ matrix.arch }} addon image
        if: ${{ env.BUILD_ARGS != '--test' }}
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            ${{ env.LATEST }} \
            ${{ env.EXTRA_TAG }} \
            --addon \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}-addon" \
            --target dao \
            --docker-hub ghcr.io/${ACTOR} \
            --version $VERSION 

      # use hass builder to create generic images
      - name: Test ${{ matrix.arch }} generic image
        if: ${{ env.BUILD_ARGS == '--test' && matrix.arch == 'amd64' }}
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            ${{ env.LATEST }} \
            ${{ env.EXTRA_TAG }} \
            --generic $VERSION \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}" \
            --target dao \
            --docker-hub ghcr.io/${ACTOR} \
            --version $VERSION 

      # use hass builder to create addon images
      - name: Test ${{ matrix.arch }} addon image
        if: ${{ env.BUILD_ARGS == '--test' && matrix.arch == 'amd64' }}
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            ${{ env.LATEST }} \
            ${{ env.EXTRA_TAG }} \
            --addon \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}-addon" \
            --target dao \
            --docker-hub ghcr.io/${ACTOR} \
            --version $VERSION 
