name: "Publish or test containers"

env:
  BUILD_ARGS: "--test"
  VERSION: "develop"

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish Images
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "i386"]

    runs-on: ubuntu-latest
    steps:
      # do a test build when it is not a release (or pre-release)
      - name: Set event to release
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "BUILD_ARGS=" >> $GITHUB_ENV

      # checkout the repo
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # Update config.yaml to reflect the correct version
      - name: Update version when release
        if: ${{ github.event_name == 'release' }}
        run: |
          sed -ie 's/^version: .*/version: ${{ github.ref_name }}/g' dao/config.yaml
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      # Add additional 'stable' tag when this is a non-rc release
      - name: Set stable on a verions without .rc
        shell: bash
        run: |
          if [[ $VERSION == *".rc"* ]]; then
            echo "this is a release candidate, not setting stable or latest tag"
            echo "LATEST=--no-latest" >> $GITHUB_ENV;
            echo "EXTRA_TAG=--additional-tag latest-rc" >> $GITHUB_ENV;
          else
            echo "this is a final release, setting stable tag"
            echo "LATEST=" >> $GITHUB_ENV;
            echo "EXTRA_TAG=--additional-tag stable" >> $GITHUB_ENV
          fi  
       
      # login to GHCR with the repository owner creds
      - name: Login to GHCR
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # use hass builder to create generic images
      - name: Publish or test ${{ matrix.arch }} image
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            ${{ env.LATEST }} \
            ${{ env.EXTRA_TAG }} \
            --generic $VERSION \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}" \
            --target dao \
            --docker-hub ghcr.io/${{ github.actor }} \
            --version $VERSION 

      # use hass builder to create addon images
      - name: Publish or test ${{ matrix.arch }} addon image
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            ${{ env.LATEST }} \
            ${{ env.EXTRA_TAG }} \
            --addon \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}-addon" \
            --target dao \
            --docker-hub ghcr.io/${{ github.actor }} \
            --version $VERSION 
