name: "Publish containers to ghcr.io"

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: text
        description: provide the release tag
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      # we choose the version either from the user suplied input
      # (when manually run)
      # or from the github ref_name
      - name: find version to checkout
        run: |
          USER_INPUT=${{ github.event.inputs.release_tag }}
          if [ "x${USER_INPUT} != "x" ]; then
            REF="ref/tags/${USER_INPUT}"
            VERSION="${USER_INPUT}"
          else
            REF="ref/tags/${{ github.ref_name }}"
            VERSION="${{ github.ref_name }}"
          fi
          echo "REF=$REF" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # checkout the specified release tag if run manually
      # this defaults to the triggered github.ref_name
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: $REF

      # Update config.yaml to reflect the correct version
      - name: Update version
        run: |
          sed -ie 's/version: develop/version: $VERSION/g' dao/config.yaml

      # Add additional 'stable' tag when this is a non-rc release
      - name: Set stable on a verions without .rc
        shell: bash
        run: |
          if [[ $VERSION == *".rc"* ]]; then
            echo "this is a release candidate, not setting stable tag"
          else
            echo "this is a final release, setting stable tag"
            echo "ADDITIONAL_TAG=stable" >> $GITHUB_ENV
          fi  
       
      # login to GHCR with the repository owner creds
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # use hass builder to create images
      - name: Publish image to GHCR
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --aarch64 \
            --i386 \
            --image "dao-{arch}" \
            --target dao \
            --docker-hub ghcr.io/${{ github.actor }} \
            --version $VERSION \
            --release-tag
            --additional-tag $ADDITIONAL_TAG
