name: "Publish main"

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: text
        description: provide the release tag
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Get version from release tag
      # ${{ github.ref_name }} contains the tag of the release
      # Update config.yaml to reflect that version
        run: |
          sed -ie 's/version: develop/version: ${{ github.ref_name }}/g' dao/config.yaml
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Set stable on a verions without .rc
        shell: bash
        run: |
          if [[ ${{ github.ref_name }} == *".rc"* ]]; then
            echo "this is a release candidate, not setting stable tag"
          else
            echo "this is a final release, setting latest tag"
            echo "ADDITIONAL_TAGS=stable" >> $GITHUB_ENV
          fi  
      - name: Publish image to GHCR
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --aarch64 \
            --i386 \
            --image "dao-{arch}" \
            --target dao \
            --docker-hub ghcr.io/${{ github.actor }} \
            --generic $GITHUB_REF_NAME \
            --version $VERSION \
            --additional-tag $ADDITIONAL_TAGS
