name: "Publish containers to ghcr.io"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "i386"]

    runs-on: ubuntu-latest
    steps:

      - name: Runs on Pre-Release
        if: 'github.event.prerelease'
        run: echo "This is a Pre-Release"
      - name: Runs on Release
        if: '!github.event.prerelease'
        run: echo "This is a Release"

      # checkout the repo
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Update config.yaml to reflect the correct version
      - name: Update version
        run: |
          sed -ie 's/version: develop/version: ${{ github.ref_name }}/g' dao/config.yaml
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      # Add additional 'stable' tag when this is a non-rc release
      - name: Set stable on a verions without .rc
        shell: bash
        run: |
          if [[ $VERSION == *".rc"* ]]; then
            echo "this is a release candidate, not setting stable tag"
            echo "ADDITIONAL_TAG=rc" >> $GITHUB_ENV
          else
            echo "this is a final release, setting stable tag"
            echo "ADDITIONAL_TAG=stable" >> $GITHUB_ENV
          fi  
       
      # login to GHCR with the repository owner creds
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # use hass builder to create generic images
      - name: Publish ${{ matrix.addon }}  image to GHCR
        uses: home-assistant/builder@master
        with:
          args: |
            --generic $VERSION \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}" \
            --target dao \
            --docker-hub ghcr.io/${{ github.actor }} \
            --version $VERSION \
            --release-tag \
            --additional-tag $ADDITIONAL_TAG

      # use hass builder to create addon images
      - name: Publish ${{ matrix.addon }}  addon image to GHCR
        uses: home-assistant/builder@master
        with:
          args: |
            --addon \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}" \
            --target dao \
            --docker-hub ghcr.io/${{ github.actor }} \
            --version $VERSION \
            --release-tag \
            --additional-tag $ADDITIONAL_TAG
