name: "Test version"

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from file
        id: get_version
        run: |
          echo ${{ github.workspace }}
          echo grep 'version: ' ${{ github.workspace }}/dao/config.yaml | sed 's/version: //'
          VERSION = $(grep 'version: ' ${{ github.workspace }}/dao/config.yaml | sed 's/version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Show version
        run: echo "Version is $VERSION"
